### ISSUE TITLE
Command failed: unzip -o /chartmaker/chartcache/Sectional-09-05-2024.zip -x '*.htm' -d 

### ISSUE THREAD

**Issue by idouiri9806** [N129BZ/chartmaker#13] opened 2024-09-22 22:10 UTC
I am using Docker and followed the instructions, but I encountered an error: Command failed: unzip -o /chartmaker/chartcache/Sectional-09-05-2024.zip -x '*.htm' -d. The process ran for 50 hours. :) . The out put is just 24 KB
```
PS C:\Users\pannam> docker run -it n129bz/chartmaker:latest /bin/bash
root@b4ba0f576c90:/# node /chartmaker/make
Running in docker!
Select:
----------------------------------------------------------------
1 = Process a single area VFR chart
2 = Process all 52 area VFR charts individually
3 = Process a single full chart from the full chart list
4 = Process all of the full charts in the full chart list
----------------------------------------------------------------
Your selection: 3

Select the full chart number you want to process from this list

0 Sectional
1 Caribbean
2 Grand Canyon
3 Terminal
4 Helicopter
5 Enroute Low
6 Enroute High
7 US VFR Wall Planning
--------------------------------------------
Your selection: 0
Created working area subfolders
Downloading /chartmaker/chartcache/Sectional-09-05-2024.zip
Command failed: curl https://aeronav.faa.gov/visual/09-05-2024/All_Files/Sectional.zip -o /chartmaker/chartcache/Sectional-09-05-2024.zip
Command failed: unzip -o /chartmaker/chartcache/Sectional-09-05-2024.zip -x '*.htm' -d /chartmaker/workarea/Sectional/1_unzipped
>> generating metadata json for Sectional database
>> creating database: /chartmaker/charts/Sectional.db
Sectional processing time: 50:47:5

Start time: Fri Sep 20 2024 19:13:51 GMT+0000 (Coordinated Universal Time)
End time: Sun Sep 22 2024 22:01:48 GMT+0000 (Coordinated Universal Time)
Total processing time: 50:47:57
```

**Comment by N129BZ** [comment] 2024-09-23 00:00
Try this: run the docker image but don't put /bin/bash at the end of tge run command, then try a single area chart, if successful it will create that area chart in less than 8 minutes or so.

**Comment by N129BZ** [comment] 2024-09-23 00:02
Try this: run the docker image but don't put /bin/bash at the end of tge run command, then try a single area chart, if successful it will create that area chart in less than 8 minutes or so.

**Comment by N129BZ** [comment] 2024-09-23 00:04
I may need to change the instructions to have users first change to the /chartmaker directory.  I think that's what the issue may be.

**Comment by N129BZ** [comment] 2024-09-23 00:04
I may need to change the instructions to have users first change to the /chartmaker directory.  I think that's what the issue may be.

**Comment by N129BZ** [comment] 2024-09-23 00:15
I updated the instructions in the readme.  The instructions on the Wiki page were correct, I apologize for your issue.  Also, to reduce processing time, before running _**node make**_, after you have changed the directory to _**/chartmaker**_, run _**nano settings.json**_ - and carefully change the zoomrange from **1-12** to **0-11**, and change the _**tileimagequality**_ value to something like **60** and then save the file and start the process with _**node make**_ and see how long it takes to run the full sectional chart.

**Comment by N129BZ** [comment] 2024-09-23 00:19
I'm also running the docker image to confirm if the issue was caused by starting the process from the root directory rather than first changing the directory to **_/chartmaker_**

**Comment by N129BZ** [comment] 2024-09-23 00:37
Also - what OS are you running docker with?

**Comment by idouiri9806** [comment] 2024-09-23 01:16
I have the latest version of macOS, but unfortunately, the Docker engine won't start. I tried it on my Windows PC and left it running, and it seemed to be working. I followed the instructions, but hey, I’m new to Docker, so I may have messed up. Anyway, thank you for clarifying. I will retry and see. You may close this issue, I will reopen it if it does the same again. Hopefully not :)

**Comment by N129BZ** [comment] 2024-09-23 01:24
It works pretty well on WSL in Windows.

**Comment by N129BZ** [comment] 2024-09-23 01:43
I think the FAA website may be undergoing maintenance or something, I got the curl failure as well, but I know it's not a problem with the code.

**Comment by N129BZ** [comment] 2024-09-24 14:51
Re-ran successfully last night, zoomrange = 0-11, image quality set at 60, see total time of 3:38 below
```
generating metadata json for Sectional database
creating database: /chartmaker/charts/Sectional.db
Sectional processing time: 3:37:58

Start time: Tue Sep 24 2024 01:17:56 GMT+0000 (Coordinated Universal Time)
End time: Tue Sep 24 2024 04:56:04 GMT+0000 (Coordinated Universal Time)
Total processing time: 3:38:8
```
**Resulting map:**
![ChartmakerSectional](https://github.com/user-attachments/assets/0c08d413-52c0-4b11-a942-e70e7df6be28)

**Comment by N129BZ** [comment] 2024-09-24 23:34
Closing issue.

**Comment by idouiri9806** [comment] 2024-10-04 10:24
Hey! I can confirm the sectional chart process is working now but I get an error when processing enroute low and enroute high?

```
Your selection: 3

Select the full chart number you want to process from this list

0 Sectional
1 Caribbean
2 Grand Canyon
3 Terminal
4 Helicopter
5 Enroute Low
6 Enroute High
7 US VFR Wall Planning
--------------------------------------------
Your selection: 5 
/chartmaker/make.js:318
        let lcasename = chart[index].toLowerCase(); 
                                     ^

TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at /chartmaker/make.js:318:38
    at Array.forEach (<anonymous>)
    at processFulls (/chartmaker/make.js:316:12)
    at processOneFull (/chartmaker/make.js:312:5)
    at Object.<anonymous> (/chartmaker/make.js:237:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)

Node.js v20.17.0
root@91dabe07f0a2:/chartmaker# node make
Select:
-----------
```

**Comment by N129BZ** [comment] 2024-10-04 17:23
Thanks for reporting. Checking it!!

**Comment by N129BZ** [comment] 2024-10-04 17:47
FIxed bug in **_Full chart processing_** where the chartname is supposed to be converted to lower case. The IFR charts are unique in that a single FAA zip file, **DDECUS**, contains both the enroute_low and enroute_high chart TIFFs.  The processing needs to know the name of the chart file, but needs to isolate those 2 different types of charts to the one the user selects.

**Closed by N129BZ** 2024-10-04 17:47 UTC
